# Generated by Django 5.0.6 on 2026-04-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('shipping_line1', models.CharField(max_length=200)),
                ('shipping_line2', models.CharField(blank=True, max_length=200)),
                ('shipping_city', models.CharField(max_length=120)),
                ('shipping_postal_code', models.CharField(max_length=30)),
                ('shipping_country', models.CharField(default='IL', max_length=2)),
                ('subtotal_cents', models.PositiveIntegerField()),
                ('shipping_cents', models.PositiveIntegerField(default=0)),
                ('total_cents', models.PositiveIntegerField()),
                ('currency', models.CharField(default='ILS', max_length=3)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending payment'), ('paid', 'Paid'), ('fulfilled', 'Fulfilled'), ('canceled', 'Canceled')], default='pending_payment', max_length=20)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=120)),
                ('stripe_client_secret', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_sku_snapshot', models.CharField(max_length=40)),
                ('product_name_en_snapshot', models.CharField(max_length=120)),
                ('product_name_he_snapshot', models.CharField(max_length=120)),
                ('product_image_snapshot', models.URLField(blank=True, max_length=500)),
                ('unit_price_cents', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
    ]
