# Generated by Django 5.0.6 on 2026-04-21 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name_en', models.CharField(max_length=80)),
                ('name_he', models.CharField(max_length=80)),
                ('description_en', models.TextField(blank=True)),
                ('description_he', models.TextField(blank=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ('display_order', 'slug'),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=40, unique=True)),
                ('name_en', models.CharField(max_length=120)),
                ('name_he', models.CharField(max_length=120)),
                ('description_en', models.TextField()),
                ('description_he', models.TextField()),
                ('ingredients_en', models.TextField(blank=True)),
                ('ingredients_he', models.TextField(blank=True)),
                ('price_cents', models.PositiveIntegerField()),
                ('currency', models.CharField(default='ILS', max_length=3)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
            options={
                'ordering': ('-is_featured', '-created_at'),
            },
        ),
    ]
